[package]
name = "rust-wildbow-scraper"
version = "0.1.0"
authors = ["Nico Hickman <nicohman@protonmail.com>"]

[dependencies]
reqwest = "0.8.5"
select = "0.4.2"
gen-epub-book = "2.2.0"
chrono = "0.4"
